### ISSUE TITLE
Demo - Can't select any goods in ASN

### ISSUE THREAD

**Issue by areman** [Singosgu/GreaterWMS#10]
Dear GreaterWMS,

the projects look very interesting to me. Create work !!

I'm just playing a little bit with the demo, but I can't create a valid ASN. I Can select a supplier but the goods selection is always empty :-( 
I've already created a Row in the Goods List. 
I don't know what's wrong. 

Best Regards

**Comment by Singosgu** [comment]
Hi Areman:

The goods selection is a Match search input . 
1.  Input arbitrary word which your goods include 
2. sellect which one you want
3. input the qty which you want to create in this ASN
4. confirm the submit

You will find the ASN status is 1 . It means you create 1 ASN which can be edit & delete.

While your Mouse Move To this ASN . It appear a purple tip . Reason is system does not match the transportation freigth. I'm not add payment website yet . But the payment api is ok for system . The system will match the city to city freight and caculate the ASN freight , Show everyone to see the freight easily . If ASN detail be changed , the freight will caculate again .

After you click confirm delivery . ASN status will change to 2 . ASN can net be edit & delete as well. It means ASN waiting for Loading , ASN has arrive you warehouse . Think: you can give your supplier a account , and let them create the ASN . When the ASN arrive warehouse , your confirm the ASN .

Release Version will be released before this month . 

Tks for your support !!

**Comment by areman** [comment]
Great !!
I understood. 
Thank you for the great work !!
