### ISSUE TITLE
Contact regarding custom integration

### ISSUE THREAD

**Issue by pclemente** [Singosgu/GreaterWMS#195]
Hi, I've tried to contact you via the website form but it doesn't work. We would be interested in talking about a custom integration for a big company, would you be open to do something like that? If so, how can I contact you. Thanks!

**Comment by Singosgu** [comment]
ok, elvis.shi@56yhz.com,  'coz we're in National holiday these days . Sorry for feedback later . you can send me somthing you want . We will feedback ASAP .
