### ISSUE TITLE
出库单的“拣货确认”中查询疑问

### ISSUE THREAD

**Issue by xslong** [Singosgu/GreaterWMS#35]
相同goods_code的出库单明细PickingList的t_code可能会一样，这个查询是不是应该加个dn_code条件？谢谢
`
 pick_qty_change = PickingListModel.objects.filter(openid=self.request.auth.openid,
                                                                  t_code=str(data['goodsData'][i].get('t_code'))).first()
`

![image](https://user-images.githubusercontent.com/5440930/124404934-953f6400-dd6f-11eb-8585-8fbae2bc14e1.png)

![image](https://user-images.githubusercontent.com/5440930/124404956-abe5bb00-dd6f-11eb-853f-a0d08c604d3d.png)

**Comment by Singosgu** [comment]
嗯，看来是个错误，需要修复。t_code是货物存储唯一标识，谢谢支持
