### ISSUE TITLE
在家部署， 路由器做端口映射之后 只能通过局域网访问

### ISSUE THREAD

**Issue by duan130196** [Singosgu/GreaterWMS#39]
家里的公网ip有域名， 做映射之后，通过外网只能访问页面， 用户无法注册无法登录，  在局域网内不影响， 请问是有这方面的屏蔽吗， 还是需要满足什么条件？

**Comment by Singosgu** [comment]
不是，你的链接被挂载了，你需要重新刷新下页面，请求地址的问题

**Comment by ssarrowcn** [comment]
我遇到同样的问题，刷新不起作用

**Comment by Singosgu** [comment]
清除缓存

**Comment by ssarrowcn** [comment]
清除缓存、无痕浏览，换了几个浏览器还是提示"网络异常"，局域网没有任何问题。

**Comment by Singosgu** [comment]
你估计是部署服务器了，baseurl改成外网ip

**Comment by ssarrowcn** [comment]
修改  ~/GreaterWMS/templates/dist/spa/statics/baseurl.js，清除缓存后可以登录，谢谢！

**Comment by duan130196** [comment]
感谢，不好意思，我的邮件可能遇到了点 刚看到这些消息， 应该是@ssarrowcn 的原因， 感谢！
